[workspace]
authors = ["gdm257 <gdm@disroot.org>"]
channels = ["conda-forge"]
name = "home"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
go-task = ">=3.45.5,<4"
uv = ">=0.9.11,<0.10"
